### ISSUE TITLE
Discussion: Relicensing

### ISSUE THREAD

**Issue by jamesturk** [jamesturk/scrapeghost#30]
I don't think the current license is the one I'll go with long term, but also know from experience the world of web scraping is a lot of people doing good work, but also a lot of spammy/abusive use cases too. I want to make this as unappealing as possible to those people, but I also know they aren't going to mind violating a license with no teeth.

I'm just sort of rambling about this publicly in case anybody reads this that has thoughts, right now I'm considering going AGPL.. but open to ideas.

**Comment by irux** [comment]
To be honest, I would say such things are inevitable. Spam would always exists. I think it is the same opinion as big enterprises having fear of releasing their ML work to the public.

In my opinion I would put an MIT license on this.

**Comment by jamesturk** [comment]
Just because they're inevitable doesn't mean I have to do free labor for them :)

**Comment by irux** [comment]
I mean AGPL is as bad as the actual license in my opinion and if you really want more people commiting to the repo, something more permissive would help ( just my opinion and speaking from what I would do)

**Comment by paultag** [comment]
@irux Hi there!

Former member of the board of directors of the Open Source Initiative, and currently a Debian ftpteam member - we're the ones who interpret the Debian Free Software Guidelines (DFSG) and define what is and is not acceptable to distribute in our archive, as well as maintain the archive folks `apt install` from.

All this to say I spend a lot of time thinking about licenses over the course of decades.

The choice to license software is a very personal one - and one that authors are free to pick. They're spending time building something useful, and they don't owe anyone anything else. Please do not apply pressure to people because they choose a license you do not prefer. I find it incredibly offputting.

**Comment by jamesturk** [comment]
All good @irux I do understand your POV but mine is a bit different on this piece of code in particular :) & good to see you here @paultag
