### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by brasfb** [jamesturk/scrapeghost#38]
Maybe more of a general scraping question, also maybe I'm in over my head & new to this. After preprocessing & Xpath/CSS selector, what gets sent to openai? 

Is it less helpful to just scrape all plain text on a page & then do auto splitter?

**Comment by jamesturk** [comment]
The matching HTML is sent to the LLM.  So if you had HTML like:

```
<html>
<div class="sidebar"> ... </div>
<main><a href="#">Something</a><div>Something Else</div></main>
<div class="footer"> ... </div>
</html>
```

And passed the selector `main`, all of the innerHTML of that element would get sent.  (If there are multiple matches they are appended together.)

Just extracting text would tend to lose context, further refinement of this library will likely entail figuring out how minimal the HTML sent can be without affecting results.  (I'm currently working on building a test corpus of sorts, since these sorts of questions need to be answered in probabilities.)
